### ISSUE TITLE
Text gradient

### ISSUE THREAD

**Issue by ecrmnn** [jordihales/hypercolor#24]
Hi. 
I stumbled upon this project today and it was exactly what I needed!
Awesome work.

This is more of a suggestion really, but I wanted to copy the gradient to use it as a text gradient and it would be great to have that as its own button.
This is easily achievable with Tailwind, but I had to google to find an example.
Simply add `text-transparent bg-clip-text` and it can be used with text.

Only a suggestion. Close if you dont think its worthwhile.

Thanks for a great project.

**Comment by markmead** [comment]
Thanks for the suggestion but I don't think it's something we will be adding at this time.
