### ISSUE TITLE
What is bg-radial-at-t in tailwind?

### ISSUE THREAD

**Issue by iwasherefirst2** [jordihales/hypercolor#26]
Hey, thank you for this amazing package!

I am using your images for tailwind and they look amazing. However, all images that use "bg-radial-at-t" do not work for me. I tried with latest v2 and v3 from Tailwind. Is this something I need to add in my tailwind config? I could not find bg-radial-at-t at tailwinds website either.

**Comment by jordihales** [comment]
Hey Buddy! 

Take a look in the tailwind.config.js file in the repo and it has all the necessary config you need to get the radial gradients working! 

Hope that helps

**Comment by iwasherefirst2** [comment]
Ohhh! There are the settings. I already added some colornames manually. Didn't know its all there. Thank you :)
