### ISSUE TITLE
Tailwind CSS Wordle alignment

### ISSUE THREAD

**Issue by ElmeriVincent** [jordihales/hypercolor#38]
On the main page when on medium sized screen the wordle text will not align properly.

![kuva](https://user-images.githubusercontent.com/77973084/163729290-b4dda2f3-40e9-4862-9324-6006bf68c54e.png)

**Comment by markmead** [comment]
Oops! Thanks for pointing that out! 🎉

PR is welcome if you wanted to take a look, if not then no worries.
