### ISSUE TITLE
Error - Downloading with grainy gradient generator

### ISSUE THREAD

**Issue by icepick4** [jordihales/hypercolor#61]
Hello, 

I tried to download a grainy gradient from the generator, in dev and in prod I have the same preview : 

![image](https://github.com/jordihales/hypercolor/assets/82316285/9cc905c4-66f3-4898-a7f8-50e0fcee9233)

But when I download, I got this image : 

![image](https://github.com/jordihales/hypercolor/assets/82316285/af0dd2ba-462e-4fed-a449-e1f1b80376c8)

I tried with another configuration and I got the same, colors change.

**Comment by markmead** [comment]
I can't replicate this. Any more detail you can give, browser, screen size?

**Comment by icepick4** [comment]
I used Opera GX, with a 2560 x 1440 pixels screen.

**Comment by qu8n** [comment]
I experienced the same issue. I'm using Arc browser (Chromium-based) and 1920 x 1080 screen.

**Comment by markmead** [comment]
Sorry for the delay, this should be fixed over here - https://hypercolor-maintained.vercel.app/

**Comment by markmead** [comment]
Should be A-OK on the main project now 🤞
