### ISSUE TITLE
Wrong grainy image downloaded

### ISSUE THREAD

**Issue by Vincenteliezer** [jordihales/hypercolor#65]
The grainy image section does not download the selected colors in the select menu.

**Comment by markmead** [comment]
Sorry for the delay, this should be fixed over here - https://hypercolor-maintained.vercel.app/

**Comment by markmead** [comment]
Should be A-OK on the main project now 🤞

**Comment by Vincenteliezer** [comment]
Yes, Working Now, Thank you!
