### ISSUE TITLE
Site is offline

### ISSUE THREAD

**Issue by markmead** [jordihales/hypercolor#69]
Creating an issue to let people know that the site is offline due to an issue with usage on Vercel. 

A ticket has been opened by @jordihales and Vercel are looking into it.

**Comment by markmead** [comment]
Vercel have not been very helpful...

In short, there was a random spike of millions of requests that hit the website in the early hours of the morning, this has completely used up (and then some) the bandwidth available on the Vercel "Hobby" plan.

From what I can see, these requests have come from nowhere. Online, there is very little talk of Hypercolor in the last week with the most popular being a Tweet with 400-ish likes. Hardly something that would kill the site.

Everything about this is unusual! I don't have the exact figures (maybe @jordihales could share some) but in Vercel you can see that these numbers make no sense. Although, it's OK, Vercel say it's legit! 🤦‍♀️ 

---

If these numbers are legitimate then that's amazing, I'm happy to be proven wrong but if they were legit, do you not think there would be:

1. Loads of conversation online about Hypercolor
2. Conversations about how the site it's currently down

It all seems weird to me. Any thoughts @vercel

**Comment by jordihales** [comment]
![WhatsApp Image 2024-02-05 at 14 42 28](https://github.com/jordihales/hypercolor/assets/46314874/df5d2fe4-0c00-4927-ade9-07b52182c16f)

As you can clearly see from the bandwidth analytics provided from @vercel Dashboard, there was a huge spike of traffic between 1-2am, this is very clearly abnormal, and looks a lot like a site crawl or header attack, with all the traffic going directly to the homepage.

Any assistance would be greatly appreciated! @leerob

**Comment by leerob** [comment]
Hey there. It does appear that someone has made hundreds of thousands of requests to your site, which has caused you to exceed the included free tier limits. If you are wanting to get the site back online right now, you can move to a paid plan. You might consider something like [rate limiting](https://vercel.com/guides/rate-limiting-edge-middleware-vercel-kv) to prevent malicious behavior if the site is being targeted.

**Comment by markmead** [comment]
Site is back up and hosted on Laravel Forge (I think) with CloudFlare to help prevent these types of attacks! 🤞 

I've added rate limiting to HyperUI, so we will see how quickly that uses up the allowance on the Vercel free tier. If all is OK, we can look to move Hypercolor onto that when the usage resets.

**Comment by markmead** [comment]
OK, so HyperUI used up the free tier in around 1 hour and then later had the site taken offline. 🙃
