### ISSUE TITLE
All flags aren't here

### ISSUE THREAD

**Issue by Nubaid-Rashid** [jordihales/hypercolor#70]
I need the canadian flag but couldn't find it I even used ctrl + f but i it's not there
`Error not enough FLAGS`
jk bout error that's just me playing with the code feature

**Comment by jordihales** [comment]
Hey bud, the flags are made using TailwindCSS gradients so there is no way of being able to create the maple leaf needed for a Canadian flag! You could create the flag without the leaf and add it in yourself but it’s not possible using Hypercolor.
