### ISSUE TITLE
Buttons don't work

### ISSUE THREAD

**Issue by zAlweNy26** [jordihales/hypercolor#71]
Hi, I found this website and it's really cool.
I only have one problem: I can't click the buttons present in the UI.
I'm talking about these two:
![image](https://github.com/jordihales/hypercolor/assets/41266342/64c662ef-efb6-4ecf-bae1-6ea73387c262)
In the browser console I don't get any error, so I don't know what is going on.
Only the button to download the image works.
I'm on Linux and I tried both Chrome and Firefox browsers, I hope it helps.

**Comment by markmead** [comment]
Look fine to me.
